num_mixtures: 10
mrange: .05
stdev: 0.1

density:
  IRMOF-1: 0.5934
  HKUST-1: 0.8791
  NU-125: 0.5783
  UIO-66 : 1.219
  ZIF-8 : 0.9246

experimental_mass:
  IRMOF-1: 15
  HKUST-1: 17
  NU-125: 19
  UIO-66: 18
  ZIF-8: 19

mofs:
  - IRMOF-1
  - HKUST-1
  - NU-125
  - UIO-66
  - ZIF-8

gases:
  - CO2
  - CH4
  - N2
  - C2H6

mof_array:
  - IRMOF-1
  - HKUST-1
  - NU-125 
